### ISSUE TITLE
有什么方法可以在不hide再show的情况下，直接修改底部弹窗的高度吗？

### ISSUE THREAD

**Issue by kakashilw** [choiceyou/FWPopupViewOC#2]
首先很感谢提供了这么好用的库。：）

我这边在使用的时候遇到一个问题：

就是我们这边先显示了一个底部弹窗，然后根据键盘高度，之后会增加这个底部弹窗的高度，用到了这个方法
- (void)resetSize:(CGSize)size isImmediateEffect:(BOOL)isImmediateEffect

不过这个方法要先hide再show，这样给用户的体验不好，有什么方法可以在不hide的情况下，直接修改这个底部弹窗的高度吗？

**Comment by choiceyou** [comment]
嗯，可以结合IQKeyboardManager库使用就可以了

**Comment by kakashilw** [comment]
> 嗯，可以结合IQKeyboardManager库使用就可以了

你好 感谢回复，不过，我遇到的问题主要是调用(void)resetSize:(CGSize)size isImmediateEffect:(BOOL)isImmediateEffect 这个方法的时候，FWPopupView会先执行hide再执行show，即相当于先隐藏然后重新又弹了一遍。

有没有什么办法是修改已经弹出的FWPopupView的size，而不是先隐藏再重新弹出呢？

**Comment by choiceyou** [comment]
嗯，了解了，目前暂时不支持你说的这种效果。不过有替代方案：你可以预先把弹窗size设置为你需要的最大size，同时弹窗背景色设置为透明的，然后只设置你当前需要显示的视图出来，这样子看上去也可以达到那个效果。
